number = 299
title = "文章"
publish = true

[[article]]
file = "2018-06-24-openstack创建虚拟机源码阅读.md"
title = "openstack创建虚拟机源码阅读.md"
pub_date = "2018-06-24"
publish = true
author = "PrivateRookie"
topic = ["python", "source_code"]
cover = "/static/assets/cover/c1.jpeg"

[[article]]
file = "2018-06-27-Bottle-框架中装饰器类和描述符应用.md"
title = "Bottle-框架中装饰器类和描述符应用.md"
pub_date = "2018-06-27"
publish = true
author = "PrivateRookie"
topic = ["python", "source_code"]
cover = "/static/assets/cover/c1.jpeg"


[[article]]
file = "2019-04-17-使用devpi搭建本地源.md"
title = "使用devpi搭建本地源.md"
pub_date = "2019-04-17"
publish = true
author = "PrivateRookie"
cover = "/static/assets/cover/c2.jpeg"

[[article]]
file = "2019-04-20-Python展开嵌套序列.md"
title = "Python展开嵌套序列.md"
pub_date = "2019-04-20"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c3.webp"

[[article]]
file = "2019-04-20-pipenv-使用简介.md"
title = "pipenv-使用简介.md"
pub_date = "2019-04-20"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c3.webp"

[[article]]
file = "2019-04-22-深度系统rust开发环境搭建.md"
title = "深度系统rust开发环境搭建.md"
pub_date = "2019-04-22"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c3.webp"

[[article]]
file = "2019-05-01-miniserve-miniserve简单美观的文件服务器.md"
title = "miniserve-miniserve简单美观的文件服务器.md"
pub_date = "2019-05-01"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c4.webp"

[[article]]
file = "2019-05-05-magnum-stein-release-new-features.md"
title = "magnum-stein-release-new-features.md"
pub_date = "2019-05-05"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c4.webp"

[[article]]
file = "2019-05-12-rust-rc.md"
title = "rust-rc.md"
pub_date = "2019-05-12"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c4.webp"

[[article]]
file = "2019-05-20-Python-Rust-迭代器类比.md"
title = "Python-Rust-迭代器类比.md"
pub_date = "2019-05-20"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c5.webp"

[[article]]
file = "2019-06-28-搭建etcd服务发现服务.md"
title = "搭建etcd服务发现服务.md"
pub_date = "2019-06-28"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c5.webp"

[[article]]
file = "2019-07-03-OpenStack允许root用户使用ssh-key登录.md"
title = "OpenStack允许root用户使用ssh-key登录.md"
pub_date = "2019-07-03"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c5.webp"

[[article]]
file = "2019-07-06-requirements.txt文件指定依赖.md"
title = "requirements.txt文件指定依赖.md"
pub_date = "2019-07-06"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-07-10-我经常使用的Rust小crate.md"
title = "我经常使用的Rust小crate.md"
pub_date = "2019-07-10"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-07-14-Rust模块与文件.md"
title = "Rust模块与文件.md"
pub_date = "2019-07-14"
publish = true
author = "PrivateRookie"
topic = ["rust", "translation"]
cover = "/static/assets/cover/c8.png"


[[article]]
file = "2019-07-18-Deepin安装Angular10+.md"
title = "Deepin安装Angular10+.md"
pub_date = "2019-07-18"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-07-25-使用OSProfiler.md"
title = "使用OSProfiler.md"
pub_date = "2019-07-25"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-07-27-windows上使用vscode-remote.md"
title = "windows上使用vscode-remote.md"
pub_date = "2019-07-27"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-08-04-使用rust-analyzer.md"
title = "使用rust-analyzer.md"
pub_date = "2019-08-04"
publish = true
author = "PrivateRookie"
topic = ["rust", "dev_env"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-08-16-Python-package安装时安装额外文件.md"
title = "Python-package安装时安装额外文件.md"
pub_date = "2019-08-16"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2019-08-31-Rust-命令行工具.md"
title = "Rust-命令行工具.md"
pub_date = "2019-08-31"
publish = true
author = "PrivateRookie"
topic = ["rust", "dev_env"]
cover = "/static/assets/cover/c9.jpeg"


[[article]]
file = "2019-09-27-Fedora-CoreOS-尝鲜.md"
title = "Fedora-CoreOS-尝鲜.md"
pub_date = "2019-09-27"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2020-01-31-rust代码风格tips.md"
title = "rust代码风格tips.md"
pub_date = "2020-01-31"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2020-02-03-log4rs-Rust-log库.md"
title = "log4rs-Rust-log库.md"
pub_date = "2020-02-03"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c14.webp"


[[article]]
file = "2020-02-29-impl-Trait-vs-dyn-Trait.md"
title = "impl-Trait-vs-dyn-Trait.md"
pub_date = "2020-02-29"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c10.webp"


[[article]]
file = "2020-03-04-nom-cheatsheet.md"
title = "nom-cheatsheet.md"
pub_date = "2020-03-04"
publish = true
author = "PrivateRookie"
topic = ["rust", "cheatsheet"]
cover = "/static/assets/cover/c7.webp"


[[article]]
file = "2020-03-09-gitlab-runner启动守护进程.md"
title = "gitlab-runner启动守护进程.md"
pub_date = "2020-03-09"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2020-06-25-Rust实现的日至收集工具.md"
title = "Rust实现的日至收集工具.md"
pub_date = "2020-06-25"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c13.webp"


[[article]]
file = "2020-07-19-typing+pyright-更正确的Python代码.md"
title = "typing+pyright-更正确的Python代码.md"
pub_date = "2020-07-19"
publish = true
author = "PrivateRookie"
topic = ["python"]
cover = "/static/assets/cover/c14.webp"


[[article]]
file = "2020-07-31-boxercrab发布.md"
title = "boxercrab发布.md"
pub_date = "2020-07-31"
publish = true
author = "PrivateRookie"
topic = ["rust", "release"]
cover = "/static/assets/cover/c16.webp"


[[article]]
file = "2020-08-30-PowerShell配置.md"
title = "PowerShell配置.md"
pub_date = "2020-08-30"
publish = true
author = "PrivateRookie"
topic = ["dev_env"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2022-03-12-Into特性实现参数多态的技巧.md"
title = "Into特性实现参数多态的技巧.md"
pub_date = "2022-03-12"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c6.webp"


[[article]]
file = "2022-06-03-闭包自动克隆捕获变量.md"
title = "闭包自动克隆捕获变量.md"
pub_date = "2022-06-03"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c6.webp"

[[article]]
file = "2023-12-03-底层依赖版本冲突.md"
title = "解决底层依赖版本冲突.md"
pub_date = "2023-12-03"
publish = true
author = "PrivateRookie"
topic = ["rust"]
cover = "/static/assets/cover/c23.webp"
