[book]
authors = ["PrivateRookie"]
language = "zh"
multilingual = false
src = "src"
title = "夜雨秋灯录"

[output.html]
google-analytics = "UA-138690523-1"

[output.html.fold]
enable = false

[build]
create-missing = false